services:
  scratchmirror:
    restart: always
    image: ghcr.io/scratchmirror:latest #自定义镜像名和版本号
    container_name: scratchmirror
    ports:
      - 3068:3068
    volumes:
      - scratchmirrordata:/file
volumes:
  scratchmirrordata:
